---
- name: Implementaion Loops
  hosts: all
  tasks:
    - name: Install s/w
      apt:
        name: "{{items.a}}"
        state: "{{item.b}}"
        update_cache: "{{item.c}}"
      with_items:
        - {a: tree,b: present,c: no}
        - {a: git,b: absent,c: no}
        - {a: maven,b: latest,c: yes}